In [1]:
import pandas as pd

months = ["Січ", "Лют", "Бер", "Кві", "Тра", "Чер",
          "Лип", "Сер", "Вер", "Жов", "Лис", "Гру"]

avg_temp = [-8, -6, 0, 8, 15, 19, 21, 20, 14, 7, 1, -5]

precip = [40, 38, 36, 38, 48, 60, 64, 52, 40, 38, 46, 44]

df = pd.DataFrame({
    "month": months,
    "avg_temp": avg_temp,
    "precip": precip,
})

df.head()

  month  avg_temp  precip
0   Січ        -8      40
1   Лют        -6      38
2   Бер         0      36
3   Кві         8      38
4   Тра        15      48

In [2]:
df.shape

(12, 3)

In [3]:
df.dtypes

month         str
avg_temp    int64
precip      int64
dtype: object

In [4]:
df.index

RangeIndex(start=0, stop=12, step=1)

In [5]:
df_by_month = df.set_index("month")
df_by_month

       avg_temp  precip
month
Січ          -8      40
Лют          -6      38
Бер           0      36
Кві           8      38
Тра          15      48
Чер          19      60
Лип          21      64
Сер          20      52
Вер          14      40
Жов           7      38
Лис           1      46
Гру          -5      44

In [6]:
df_by_month.loc["Тра"]

avg_temp    15
precip      48
Name: Тра, dtype: int64

In [7]:
df = df_by_month.reset_index()
df

   month  avg_temp  precip
0    Січ        -8      40
1    Лют        -6      38
2    Бер         0      36
3    Кві         8      38
4    Тра        15      48
5    Чер        19      60
6    Лип        21      64
7    Сер        20      52
8    Вер        14      40
9    Жов         7      38
10   Лис         1      46
11   Гру        -5      44

In [8]:
df.index = range(1, 13)
df

   month  avg_temp  precip
1    Січ        -8      40
2    Лют        -6      38
3    Бер         0      36
4    Кві         8      38
5    Тра        15      48
6    Чер        19      60
7    Лип        21      64
8    Сер        20      52
9    Вер        14      40
10   Жов         7      38
11   Лис         1      46
12   Гру        -5      44

In [9]:
df.loc[1:6, "avg_temp"]

1    -8
2    -6
3     0
4     8
5    15
6    19
Name: avg_temp, dtype: int64

In [10]:
df.iloc[0:6, 1]

1    -8
2    -6
3     0
4     8
5    15
6    19
Name: avg_temp, dtype: int64

In [11]:
df[["month", "precip"]]

   month  precip
1    Січ      40
2    Лют      38
3    Бер      36
4    Кві      38
5    Тра      48
6    Чер      60
7    Лип      64
8    Сер      52
9    Вер      40
10   Жов      38
11   Лис      46
12   Гру      44

In [12]:
df[df["avg_temp"] > 15][["month", "avg_temp"]]

  month  avg_temp
6   Чер        19
7   Лип        21
8   Сер        20

In [13]:
df[(df["avg_temp"] > 10) & (df["precip"] > 50)][["month", "avg_temp", "precip"]]

  month  avg_temp  precip
6   Чер        19      60
7   Лип        21      64
8   Сер        20      52

In [14]:
df[(df["avg_temp"] < 0) | (df["precip"] > 80)][["month", "avg_temp", "precip"]]

   month  avg_temp  precip
1    Січ        -8      40
2    Лют        -6      38
12   Гру        -5      44

In [15]:
df["avg_temp_f"] = df["avg_temp"] * 9 / 5 + 32
df

   month  avg_temp  precip  avg_temp_f
1    Січ        -8      40        17.6
2    Лют        -6      38        21.2
3    Бер         0      36        32.0
4    Кві         8      38        46.4
5    Тра        15      48        59.0
6    Чер        19      60        66.2
7    Лип        21      64        69.8
8    Сер        20      52        68.0
9    Вер        14      40        57.2
10   Жов         7      38        44.6
11   Лис         1      46        33.8
12   Гру        -5      44        23.0

In [16]:
df["precip"].mean()

np.float64(45.333333333333336)

In [17]:
df["is_wet"] = df["precip"] > df["precip"].mean()
df

   month  avg_temp  precip  avg_temp_f  is_wet
1    Січ        -8      40        17.6   False
2    Лют        -6      38        21.2   False
3    Бер         0      36        32.0   False
4    Кві         8      38        46.4   False
5    Тра        15      48        59.0    True
6    Чер        19      60        66.2    True
7    Лип        21      64        69.8    True
8    Сер        20      52        68.0    True
9    Вер        14      40        57.2   False
10   Жов         7      38        44.6   False
11   Лис         1      46        33.8    True
12   Гру        -5      44        23.0   False

In [18]:
def get_season(month_number):
    if month_number in [12, 1, 2]:
        return "зима"
    elif month_number in [3, 4, 5]:
        return "весна"
    elif month_number in [6, 7, 8]:
        return "літо"
    else:
        return "осінь"

In [19]:
df["season"] = df.index.to_series().apply(get_season)
df

   month  avg_temp  precip  avg_temp_f  is_wet season
1    Січ        -8      40        17.6   False   зима
2    Лют        -6      38        21.2   False   зима
3    Бер         0      36        32.0   False  весна
4    Кві         8      38        46.4   False  весна
5    Тра        15      48        59.0    True  весна
6    Чер        19      60        66.2    True   літо
7    Лип        21      64        69.8    True   літо
8    Сер        20      52        68.0    True   літо
9    Вер        14      40        57.2   False  осінь
10   Жов         7      38        44.6   False  осінь
11   Лис         1      46        33.8    True  осінь
12   Гру        -5      44        23.0   False   зима

In [20]:
df

   month  avg_temp  precip  avg_temp_f  is_wet season
1    Січ        -8      40        17.6   False   зима
2    Лют        -6      38        21.2   False   зима
3    Бер         0      36        32.0   False  весна
4    Кві         8      38        46.4   False  весна
5    Тра        15      48        59.0    True  весна
6    Чер        19      60        66.2    True   літо
7    Лип        21      64        69.8    True   літо
8    Сер        20      52        68.0    True   літо
9    Вер        14      40        57.2   False  осінь
10   Жов         7      38        44.6   False  осінь
11   Лис         1      46        33.8    True  осінь
12   Гру        -5      44        23.0   False   зима

## Письмові відповіді

### 1. Різниця між `.loc[1:6]` та `.iloc[0:6]`

`.loc` виконує вибір рядків за мітками індексу, а `.iloc` — за їхніми позиціями. Тому `.loc[1:6]` шукає рядки з мітками від 1 до 6 включно, а `.iloc[0:6]` вибирає перші шість рядків за позиціями 0–5. Кількість результатів може відрізнятися, якщо індекс не збігається з позиціями.

### 2. Чому `and` викликає помилку?

Вираз `df["avg_temp"] > 10 and df["precip"] > 50` викликає помилку, тому що `and` призначений для одиничних булевих значень, а pandas Series містить багато значень. Для поелементного логічного порівняння потрібно використовувати `&` та брати кожну умову в дужки:

`(df["avg_temp"] > 10) & (df["precip"] > 50)`.

### 3. Різниця між формулою та `.apply()`

Обчислюваний стовпець через формулу виконує однакову математичну операцію над усіма значеннями стовпця. `.apply()` дозволяє застосувати власну функцію до кожного значення та реалізувати складнішу логіку, наприклад визначення пори року.

**Практика 2. pandas: побудова DataFrame**  
**Варіант 9 — місто Суми**  
**Студент: Коць Артем**  
**Група: ІТ-42**