In [1]:
# Практика 9. Перетворення даних
# Коць Артем, ІТ-42
# Варіант 9 — Суми

import numpy as np
import pandas as pd

customers = pd.DataFrame({
    "вік": [19, 24, 31, 38, 45, 52, 27, 61, 34, 68],
    "дохід": [18000, 24000, 32000, 41000, 50000, 58000, 27000, 65000, 36000, 72000],
    "кількість": [2, 3, 1, 4, 2, 3, 5, 2, 3, 1],
    "місто_доставки": [
        "Суми",
        "Київ",
        "Львів",
        "Одеса",
        "Суми",
        "Харків",
        "Полтава",
        "Київ",
        "Суми",
        "Дніпро"
    ]
})

customers

   вік  дохід  кількість місто_доставки
0   19  18000          2           Суми
1   24  24000          3           Київ
2   31  32000          1          Львів
3   38  41000          4          Одеса
4   45  50000          2           Суми
5   52  58000          3         Харків
6   27  27000          5        Полтава
7   61  65000          2           Київ
8   34  36000          3           Суми
9   68  72000          1         Дніпро

In [2]:
base_price = 730

customers["сума_замовлення"] = (
    base_price * customers["кількість"]
)

customers["частка_доходу"] = (
    customers["сума_замовлення"] / customers["дохід"]
)

customers

   вік  дохід  кількість місто_доставки  сума_замовлення  частка_доходу
0   19  18000          2           Суми             1460       0.081111
1   24  24000          3           Київ             2190       0.091250
2   31  32000          1          Львів              730       0.022812
3   38  41000          4          Одеса             2920       0.071220
4   45  50000          2           Суми             1460       0.029200
5   52  58000          3         Харків             2190       0.037759
6   27  27000          5        Полтава             3650       0.135185
7   61  65000          2           Київ             1460       0.022462
8   34  36000          3           Суми             2190       0.060833
9   68  72000          1         Дніпро              730       0.010139

### Завдання 2. Похідна змінна

Стовпець "сума_замовлення" обчислено як добуток базової ціни
730 грн на кількість товарів у замовленні.

Стовпець "частка_доходу" показує, яку частину місячного доходу
клієнта становить його замовлення.

Ця змінна може бути кориснішою для аналізу поведінки клієнтів,
оскільки враховує не тільки розмір замовлення, а й фінансові
можливості клієнта. Однакова сума замовлення може мати зовсім
різне значення для клієнтів із різним доходом.

In [3]:
customers["вікова_група_cut"] = pd.cut(
    customers["вік"],
    bins=3
)

customers["вікова_група_cut"].value_counts().sort_index()

вікова_група_cut
(18.951, 35.333]    5
(35.333, 51.667]    2
(51.667, 68.0]      3
Name: count, dtype: int64

In [4]:
customers["вікова_група_qcut"] = pd.qcut(
    customers["вік"],
    q=3
)

customers["вікова_група_qcut"].value_counts().sort_index()

вікова_група_qcut
(18.999, 31.0]    4
(31.0, 45.0]      3
(45.0, 68.0]      3
Name: count, dtype: int64

### Завдання 3. Порівняння cut() і qcut()

Метод `pd.cut()` ділить діапазон значень на інтервали однакової
довжини. Тому кількість клієнтів у різних групах може сильно
відрізнятися, якщо значення віку розподілені нерівномірно.

Метод `pd.qcut()` ділить дані за квантилями та намагається створити
групи з приблизно однаковою кількістю спостережень. При цьому межі
вікових інтервалів можуть мати різну довжину.

Отже, `cut()` забезпечує однакову ширину інтервалів, а `qcut()`
забезпечує приблизно однакову кількість спостережень у групах.
Саме тому результати та розміри груп відрізняються, хоча вхідні
дані однакові.

In [5]:
customers["вік_minmax"] = (
    (customers["вік"] - customers["вік"].min()) /
    (customers["вік"].max() - customers["вік"].min())
)

customers["дохід_minmax"] = (
    (customers["дохід"] - customers["дохід"].min()) /
    (customers["дохід"].max() - customers["дохід"].min())
)

customers[[
    "вік",
    "дохід",
    "вік_minmax",
    "дохід_minmax"
]].head()

   вік  дохід  вік_minmax  дохід_minmax
0   19  18000    0.000000      0.000000
1   24  24000    0.102041      0.111111
2   31  32000    0.244898      0.259259
3   38  41000    0.387755      0.425926
4   45  50000    0.530612      0.592593

In [6]:
customers["вік_z"] = (
    (customers["вік"] - customers["вік"].mean()) /
    customers["вік"].std()
)

customers["дохід_z"] = (
    (customers["дохід"] - customers["дохід"].mean()) /
    customers["дохід"].std()
)

customers[[
    "вік",
    "дохід",
    "вік_minmax",
    "дохід_minmax",
    "вік_z",
    "дохід_z"
]].head()

   вік  дохід  вік_minmax  дохід_minmax     вік_z   дохід_z
0   19  18000    0.000000      0.000000 -1.284982 -1.328731
1   24  24000    0.102041      0.111111 -0.977570 -1.000649
2   31  32000    0.244898      0.259259 -0.547193 -0.563207
3   38  41000    0.387755      0.425926 -0.116817 -0.071084
4   45  50000    0.530612      0.592593  0.313560  0.421038

### Завдання 4. Масштабування

Метод min-max нормалізації переводить значення віку та доходу
до спільного діапазону [0, 1]. Це дозволяє порівнювати змінні,
які спочатку мають різний масштаб.

Z-оцінка стандартизує змінні відносно їхнього середнього значення
та стандартного відхилення. Після стандартизації середнє значення
змінної дорівнює приблизно 0, а стандартне відхилення — приблизно 1.

До масштабування вік і дохід не можна було напряму порівнювати
або використовувати разом у методах, чутливих до масштабу, оскільки
дохід має значно більші числові значення. У такому випадку дохід
міг би непропорційно сильно впливати на результат.

Масштабування усуває цю проблему та дозволяє змінним мати
порівнюваний внесок у методах, чутливих до масштабу.

In [7]:
city_dummies = pd.get_dummies(
    customers["місто_доставки"],
    prefix="місто"
)

customers = pd.concat(
    [customers, city_dummies],
    axis=1
)

city_dummies

,місто_Дніпро,місто_Київ,місто_Львів,місто_Одеса,місто_Полтава,місто_Суми,місто_Харків
0,False,False,False,False,False,True,False
1,False,True,False,False,False,False,False
2,False,False,True,False,False,False,False
3,False,False,False,True,False,False,False
4,False,False,False,False,False,True,False
5,False,False,False,False,False,False,True
6,False,False,False,False,True,False,False
7,False,True,False,False,False,False,False
8,False,False,False,False,False,True,False
9,True,False,False,False,False,False,False

In [8]:
print("Унікальних міст:", customers["місто_доставки"].nunique())
print("Нових one-hot стовпців:", len(city_dummies.columns))

Унікальних міст: 7
Нових one-hot стовпців: 7

### Завдання 5. Індикаторне кодування

Для змінної "місто_доставки" використано one-hot кодування
за допомогою pd.get_dummies().

У наборі даних є 6 унікальних міст, тому було створено 6
індикаторних стовпців. Для кожного рядка відповідний стовпець
має значення True, якщо замовлення доставляється до цього міста,
і False в іншому випадку.

One-hot кодування є правильним для міста, оскільки міста є
номінальною категорією і не мають природного порядку. Якщо
замапити міста у числа 1, 2, 3 тощо, це створило б помилкове
враження, що одне місто "більше" або "вище" за інше.

Тому для номінальної змінної "місто_доставки" доцільно
використовувати саме one-hot кодування.

In [9]:
customers

,вік,дохід,кількість,місто_доставки,сума_замовлення,частка_доходу,вікова_група_cut,вікова_група_qcut,вік_minmax,дохід_minmax,вік_z,дохід_z,місто_Дніпро,місто_Київ,місто_Львів,місто_Одеса,місто_Полтава,місто_Суми,місто_Харків
0,19,18000,2,Суми,1460,0.081111,"(18.951, 35.333]","(18.999, 31.0]",0.000000,0.000000,-1.284982,-1.328731,False,False,False,False,False,True,False
1,24,24000,3,Київ,2190,0.091250,"(18.951, 35.333]","(18.999, 31.0]",0.102041,0.111111,-0.977570,-1.000649,False,True,False,False,False,False,False
2,31,32000,1,Львів,730,0.022812,"(18.951, 35.333]","(18.999, 31.0]",0.244898,0.259259,-0.547193,-0.563207,False,False,True,False,False,False,False
3,38,41000,4,Одеса,2920,0.071220,"(35.333, 51.667]","(31.0, 45.0]",0.387755,0.425926,-0.116817,-0.071084,False,False,False,True,False,False,False
4,45,50000,2,Суми,1460,0.029200,"(35.333, 51.667]","(31.0, 45.0]",0.530612,0.592593,0.313560,0.421038,False,False,False,False,False,True,False
5,52,58000,3,Харків,2190,0.037759,"(51.667, 68.0]","(45.0, 68.0]",0.673469,0.740741,0.743937,0.858481,False,False,False,False,False,False,True
6,27,27000,5,Полтава,3650,0.135185,"(18.951, 35.333]","(18.999, 31.0]",0.163265,0.166667,-0.793123,-0.836608,False,False,False,False,True,False,False
7,61,65000,2,Київ,1460,0.022462,"(51.667, 68.0]","(45.0, 68.0]",0.857143,0.870370,1.297278,1.241243,False,True,False,False,False,False,False
8,34,36000,3,Суми,2190,0.060833,"(18.951, 35.333]","(31.0, 45.0]",0.306122,0.333333,-0.362746,-0.344486,False,False,False,False,False,True,False
9,68,72000,1,Дніпро,730,0.010139,"(51.667, 68.0]","(45.0, 68.0]",1.000000,1.000000,1.727655,1.624005,True,False,False,False,False,False,False

## Контрольні питання

### 1. У чому різниця між pd.cut() і pd.qcut()?

`pd.cut()` ділить діапазон числових значень на інтервали однакової
довжини. Кількість спостережень у групах при цьому може бути різною.

`pd.qcut()` ділить дані за квантилями та намагається створити групи
з приблизно однаковою кількістю спостережень. Межі інтервалів при
цьому можуть бути різної довжини.

### 2. Чому для міста застосовують one-hot кодування?

Місто є номінальною змінною і не має природного порядку. Кодування
міст числами 1, 2, 3 тощо створило б хибний порядок і відстань між
категоріями.

One-hot кодування створює окремий індикатор для кожного міста та
не вносить штучного порядку між категоріями.

### 3. Навіщо масштабувати змінні перед методами, чутливими до масштабу?

Змінні можуть мати дуже різні діапазони значень. У нашому випадку
вік вимірюється десятками років, а дохід — десятками тисяч гривень.

У дистанційних методах або моделях із регуляризацією змінна з більшим
числовим масштабом може отримати непропорційно великий вплив.
Масштабування приводить змінні до порівнюваної шкали.

### 4. Чому похідна змінна може бути кориснішою за вихідні складники?

Похідна змінна може показувати співвідношення між двома показниками,
яке має безпосередній практичний зміст.

Наприклад, "частка_доходу" показує, яку частину місячного доходу
клієнта становить замовлення. Тому вона дає змогу порівнювати
фінансове навантаження від замовлення для клієнтів із різним доходом,
чого не можна побачити лише за сумою замовлення або доходом окремо.